# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
lune = "lune-org/lune@0.10.4"
pesde = "pesde-pkg/pesde@0.7.2+registry.0.2.3"
rojo = "rojo-rbx/rojo@7.6.1"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
